// packages/account-ui/src/frameworks/vue/BasePayButton.vue
<!-- BasePayButton.vue -->
<template>
  <div ref="mountPoint" :style="{ display: 'block', width: '100%' }" />
</template>

<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from 'vue';
import { BasePayButtonProps } from '../../types.js';
import { mountBasePayButton, unmountBasePayButton } from '../preact/mountBasePayButton.js';

interface Props extends BasePayButtonProps {}

const props = withDefaults(defineProps<Props>(), {
  colorScheme: 'system',
});

const mountPoint = ref<HTMLElement | null>(null);

const mountWidget = () => {
  if (mountPoint.value) {
    // Clone props to avoid extensibility issues
    const clonedProps = { ...props };
    mountBasePayButton(mountPoint.value, clonedProps);
  }
};

const unmountWidget = () => {
  if (mountPoint.value) {
    unmountBasePayButton(mountPoint.value);
  }
};

onMounted(() => {
  mountWidget();
});

onBeforeUnmount(() => {
  unmountWidget();
});

// Watch for prop changes and re-mount the component
watch(
  () => props,
  () => {
    unmountWidget();
    mountWidget();
  },
  { deep: true }
);
</script>

// packages/account-ui/src/frameworks/svelte/BasePayButton.svelte
<script>
import { afterUpdate, onDestroy, onMount } from 'svelte';
import { mountBasePayButton, unmountBasePayButton } from '../preact/mountBasePayButton.js';

// Props with defaults
export let colorScheme = 'system';
export let onClick = undefined;

let mountPoint;
let previousProps = {};

const mountWidget = () => {
  if (mountPoint) {
    // Clone props to avoid extensibility issues
    const clonedProps = { colorScheme, onClick };
    mountBasePayButton(mountPoint, clonedProps);
    previousProps = { ...clonedProps };
  }
};

const unmountWidget = () => {
  if (mountPoint) {
    unmountBasePayButton(mountPoint);
  }
};

const hasPropsChanged = () => {
  const currentProps = { colorScheme, onClick };
  return JSON.stringify(currentProps) !== JSON.stringify(previousProps);
};

onMount(() => {
  mountWidget();
});

afterUpdate(() => {
  if (mountPoint && hasPropsChanged()) {
    unmountWidget();
    mountWidget();
  }
});

onDestroy(() => {
  unmountWidget();
});
</script>

<div bind:this={mountPoint} style="display: block; width: 100%;"></div>
