// packages/account-ui/src/frameworks/vue/SignInWithBaseButton.vue
<!-- SignInWithBaseButton.vue -->
<template>
  <div ref="mountPoint" :style="{ display: 'block', width: '100%' }" />
</template>

<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from 'vue';
import { SignInWithBaseButtonProps } from '../../types.js';
import {
  mountSignInWithBaseButton,
  unmountSignInWithBaseButton,
} from '../preact/mountSignInWithBaseButton.js';

interface Props extends SignInWithBaseButtonProps {}

const props = withDefaults(defineProps<Props>(), {
  align: 'center',
  variant: 'solid',
  colorScheme: 'system',
});

const mountPoint = ref<HTMLElement | null>(null);

const mountWidget = () => {
  if (mountPoint.value) {
    // Clone props to avoid extensibility issues
    const clonedProps = { ...props };
    mountSignInWithBaseButton(mountPoint.value, clonedProps);
  }
};

const unmountWidget = () => {
  if (mountPoint.value) {
    unmountSignInWithBaseButton(mountPoint.value);
  }
};

onMounted(() => {
  mountWidget();
});

onBeforeUnmount(() => {
  unmountWidget();
});

// Watch for prop changes and re-mount the component
watch(
  () => props,
  () => {
    unmountWidget();
    mountWidget();
  },
  { deep: true }
);
</script>

// packages/account-ui/src/frameworks/svelte/SignInWithBaseButton.svelte
<script>
import { afterUpdate, onDestroy, onMount } from 'svelte';
import {
  mountSignInWithBaseButton,
  unmountSignInWithBaseButton,
} from '../preact/mountSignInWithBaseButton.js';

// Props with defaults
export let align = 'center';
export let variant = 'solid';
export let colorScheme = 'system';
export let onClick = undefined;

let mountPoint;
let previousProps = {};

const mountWidget = () => {
  if (mountPoint) {
    // Clone props to avoid extensibility issues
    const clonedProps = { align, variant, colorScheme, onClick };
    mountSignInWithBaseButton(mountPoint, clonedProps);
    previousProps = { ...clonedProps };
  }
};

const unmountWidget = () => {
  if (mountPoint) {
    unmountSignInWithBaseButton(mountPoint);
  }
};

const hasPropsChanged = () => {
  const currentProps = { align, variant, colorScheme, onClick };
  return JSON.stringify(currentProps) !== JSON.stringify(previousProps);
};

onMount(() => {
  mountWidget();
});

afterUpdate(() => {
  if (mountPoint && hasPropsChanged()) {
    unmountWidget();
    mountWidget();
  }
});

onDestroy(() => {
  unmountWidget();
});
</script>

<div bind:this={mountPoint} style="display: block; width: 100%;"></div>
