// packages/account-ui/src/frameworks/vue/SignInWithBaseButton.vue
<!-- SignInWithBaseButton.vue -->
<template>
  <div ref="mountPoint" :style="{ display: 'block', width: '100%' }" />
</template>

<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from 'vue';
import { SignInWithBaseButtonProps } from '../../types.js';
import {
  mountSignInWithBaseButton,
  unmountSignInWithBaseButton,
} from '../preact/mountSignInWithBaseButton.js';

interface Props extends SignInWithBaseButtonProps {}

const props = withDefaults(defineProps<Props>(), {
  align: 'center',
  variant: 'solid',
  colorScheme: 'system',
});

const mountPoint = ref<HTMLElement | null>(null);

const mountWidget = () => {
  if (mountPoint.value) {
    // Clone props to avoid extensibility issues
    const clonedProps = { ...props };
    mountSignInWithBaseButton(mountPoint.value, clonedProps);
  }
};

const unmountWidget = () => {
  if (mountPoint.value) {
    unmountSignInWithBaseButton(mountPoint.value);
  }
};

onMounted(() => {
  mountWidget();
});

onBeforeUnmount(() => {
  unmountWidget();
});

// Watch for prop changes and re-mount the component
watch(
  () => props,
  () => {
    unmountWidget();
    mountWidget();
  },
  { deep: true }
);
</script>

// packages/account-ui/src/frameworks/react/SignInWithBaseButton.ts
import { FC, createElement, useEffect, useRef } from 'react';
import { SignInWithBaseButtonProps } from '../../types.js';
import {
  mountSignInWithBaseButton,
  unmountSignInWithBaseButton,
} from '../preact/mountSignInWithBaseButton.js';

export const SignInWithBaseButton: FC<SignInWithBaseButtonProps> = (
  props: SignInWithBaseButtonProps
) => {
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (ref.current) {
      // Clone props to avoid extensibility issues between React and Preact
      const clonedProps = { ...props };
      mountSignInWithBaseButton(ref.current, clonedProps);
    }

    return () => {
      if (ref.current) {
        unmountSignInWithBaseButton(ref.current);
      }
    };
  }, [props]);

  return createElement('div', {
    ref,
    style: {
      display: 'block',
      width: '100%',
    },
  });
};
